apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rk1qf32ut-nodejs
  janus-idp.io/tekton: rk1qf32ut-nodejs
  backstage.io/kubernetes-id: rk1qf32ut-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rk1qf32ut-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
